name: adaptive_dialog_views
description: "Description here"
#publish_to: 'none'
repository: https://github.com/juneview-songdo/adaptive_dialog_views

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  adaptive_dialog: ^2.1.0 #@add
  after_layout:
  bot_toast:
  device_preview:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  flutter_zoom_drawer:
  gap:
  go_router:
  june:
  june_flow_util:
  keyboard_attachable:
  modal_bottom_sheet:
  styled_widget:


dev_dependencies:
  adaptive_dialog_module:
  bot_toast_module:
  config_theme: #@add
  device_preview_module:
  flutter_lints:
  flutter_lints_module:
  flutter_test:
    sdk: flutter
  june_view:  #@add
  june_view_more:  #@add
  screenutil_module:

flutter:
  assets:
    - assets/module/config_theme/
    - assets/view/adaptive_dialog_views/
  uses-material-design: true